spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Reaktor_SchoolAutomationServer?createDatabaseIfNotExist=true
    username: root
    password: toor
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
